/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_customer;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import ui_generic.LoginPage;
/**
 *
 * @author User
 */
public class CustomerReceipt extends javax.swing.JFrame {
    private static final DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
    Date currentDate = new Date();
    Calendar c = Calendar.getInstance();
    Date editedDate;
    String editedDateString;

    /**
     * Creates new form CustomerReceipt
     */
    public CustomerReceipt() {
        initComponents();
        c.setTime(currentDate);
        c.add(Calendar.DATE, CustomerVehicleDetails.daysSelected);
        editedDate = c.getTime();
        editedDateString = dateFormat.format(editedDate);
        CustomerName.setText(LoginPage.customerLoggedIn.getFirstName() + " " + LoginPage.customerLoggedIn.getSurname());
        PurchasedVehicle.setText(CustomerVehicleDetails.carSelected.getMake() + " " + CustomerVehicleDetails.carSelected.getModel());
        TotalPrice.setText("£" + CustomerVehicleDetails.totalPrice);
        Date.setText(new SimpleDateFormat("dd-MM-yyyy").format(new Date()));  
        ReturnDate.setText("Return date: " + editedDateString); 
        
        LoginPage.customerLoggedIn.setVehicleHired(CustomerVehicleDetails.carSelected.getMake() + " " + CustomerVehicleDetails.carSelected.getModel());
        CustomerVehicleDetails.carSelected.setIsAvailable(false);
        CustomerVehicleDetails.carSelected.setDateReturning(editedDateString);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Date = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CustomerName = new javax.swing.JLabel();
        PurchasedVehicle = new javax.swing.JLabel();
        ReturnDate = new javax.swing.JLabel();
        TotalPrice = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Date.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        jLabel2.setText("Mutley Motor Hire");
        jLabel2.setToolTipText("");

        CustomerName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CustomerName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CustomerName.setText("jLabel1");

        PurchasedVehicle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PurchasedVehicle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PurchasedVehicle.setText("jLabel1");

        ReturnDate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ReturnDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ReturnDate.setText("jLabel1");

        TotalPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalPrice.setText("jLabel1");

        jButton1.setText("To menu ->");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ReturnDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PurchasedVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addComponent(Date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(CustomerName)
                .addGap(37, 37, 37)
                .addComponent(PurchasedVehicle)
                .addGap(29, 29, 29)
                .addComponent(TotalPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(ReturnDate)
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        CustomerMenu cMenu = new CustomerMenu();
        cMenu.setVisible(true);
        cMenu.pack();
        cMenu.setLocationRelativeTo(null);
        this.dispose();    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustomerName;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel PurchasedVehicle;
    private javax.swing.JLabel ReturnDate;
    private javax.swing.JLabel TotalPrice;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
