/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui_admin;

import ui_customer.*;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import models.VehicleManager;
import products.Car;

/**
 *
 * @author User
 */
public class AdminVehicleMenu extends javax.swing.JFrame {
    public static int rowSelected;

    /**
     * Creates new form CustomerShopMenu
     */
    public AdminVehicleMenu() {
        initComponents();
        ArrayList<Car> newCarList = VehicleManager.getInstance().getCarList();
        Car test1 = new Car(true, 200, "10/10/10", null, "honda", "civic", "1029283");
        Car test2 = new Car(true, 400, "20/12/11", null, "honda", "massau", "69696969");
        newCarList.add(test1);
        newCarList.add(test2);
        addRowToJTable();
        ListSelectionModel sModel = VehicleDisplay.getSelectionModel();
        sModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (! sModel.isSelectionEmpty()) {
                    rowSelected = sModel.getMinSelectionIndex();
                    loadDetails();
                }
            }
        });

    }
    
    public void loadDetails() {
    AdminVehicleDetails adminVD = new AdminVehicleDetails();
    adminVD.setVisible(true);
    adminVD.pack();
    adminVD.setLocationRelativeTo(null);   
    this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        VehicleDisplay = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setToolTipText("");
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        VehicleDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Make", "Model", "Registration", "Price Per Day", "Available", "Date Returning"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        VehicleDisplay.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(VehicleDisplay);
        if (VehicleDisplay.getColumnModel().getColumnCount() > 0) {
            VehicleDisplay.getColumnModel().getColumn(0).setResizable(false);
            VehicleDisplay.getColumnModel().getColumn(1).setResizable(false);
            VehicleDisplay.getColumnModel().getColumn(2).setResizable(false);
            VehicleDisplay.getColumnModel().getColumn(3).setResizable(false);
            VehicleDisplay.getColumnModel().getColumn(4).setResizable(false);
            VehicleDisplay.getColumnModel().getColumn(5).setResizable(false);
        }

        BackButton.setText("<- Back");
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BackButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackButton)
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        AdminMenu aMenu = new AdminMenu();
        aMenu.setVisible(true);
        aMenu.pack();
        aMenu.setLocationRelativeTo(null);
        this.dispose();    }//GEN-LAST:event_BackButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminVehicleMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminVehicleMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminVehicleMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminVehicleMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminVehicleMenu().setVisible(true);
            }
        });
    }
    
    public void addRowToJTable() {
        DefaultTableModel model = (DefaultTableModel) VehicleDisplay.getModel();
        Object rowData[] = new Object[6];
        for (Car v : VehicleManager.getInstance().getCarList()) {
            rowData[0] = v.getMake();
            rowData[1] = v.getModel();
            rowData[2] = v.getRegDetails();
            rowData[3] = "£" + Integer.toString(v.getPrice());
            rowData[4] = v.getIsAvailable();
            rowData[5] = v.getDateReturning();
            model.addRow(rowData);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTable VehicleDisplay;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
